name: Trigger backend-b workflow from backend-a workflow
on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  build:
    name: Run backend-a application
    runs-on: ubuntu-latest
    steps:
      - name: Build backend-a application
        run: echo "Build backend a application"
      
