name: Trigger backend-b workflow from backend-a workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run backend-a application
    runs-on: ubuntu-latest
    steps:
      - name: Build backend-a application
        run: |
          echo "Should not run this one as backend-b failed"
          echo "Build backend a application"
    
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: dmallick89
          repo: backend-b
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          workflow_file_name: backend.yml
      
